API/urls.py
from django.urls import path, include
from rest_framework import routers
from API import views

router=routers.DefaultRouter()
router.register(r'producto', views.ProductoViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

xan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('API.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

API/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    id = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=200)
    precio = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return str(self.id)+" "+str(self.nombre)

web/templates/web/producto/agregar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap, iconos de bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- hojas de estilos, css, fuentes, colores-->
    <link rel="stylesheet" href="{% static '/CSS/menu.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/carrusel.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/style_footer.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/paragraph_index.css' %}"> 
    <!-- fin de imports de estilo (css) -->
    <!-- Favicon, icono de la pestaña, luego va el tamaño(para diferentes tipo de dispositivo)-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/imgs/favicon/apple-touch-icon.png' %}"><!-- este es para apple-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/imgs/favicon/avicon-32x32.png' %}"><!-- este es para windows-->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/imgs/favicon/favicon-16x16.png' %}"><!-- este es para android-->
    <link rel="manifest" href="{% static '/imgs/favicon/site.webmanifest' %}">
    <!-- fin Favicon -->

    <title>Xan Proxy</title> <!--Titulo de las pestañas -->
</head>

<body>
    <!-- menu -->
    <header class="header"> <!--Clase header-->
        <nav> <!--Nav viene de la palabra navigator o sea esta nos mandará a los links que esten dentro de esta misma o los podemos redireccionar donde sea deseado-->
            <ul class="sidebar"> <!--Clase barra lateral, contiene una lista y anclas(anchors) a las otras paginas de nuestro sitio web-->
                <li onclick=hideSidebar()><a href="#"><i class="bi bi-x-lg"></i></a></li>
                <li><a href="{% url 'index' %}">Inicio</a></li> <!-- link a index-->
                <li><a href="{% url 'info' %}">Sobre Xan</a></li><!-- link a info chan-->
                <li><a href="{% url 'portafolio' %}">Portafolio</a></li><!-- link a portafolio de imagenes-->
                <li><a href="{% url 'patreon' %}">Comisiones</a></li> <!--Link a patreon-->
                <li><a href="{% url 'referencia' %}">Referencias</a></li>

                {% if perms.web.add_producto %}
                <li><a href="">Agregar Prod.</a></li>
                {% endif %}

                {% if perms.web.view_producto %}
                <li><a href="{% url 'listar_producto' %}">Listado de Prod.</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                    </form>
                </li>
                <li>
                    <a href="#">@{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Iniciar sesión</a>
                </li>
                {% endif %}


            </ul> <!--unordered list -->
            <ul> <!--Esto cambia si es que lo veo de mi dispositivo movil  y me agrega un pequeño boton de menu lateral en la esquina superior izquierda-->
                <li><img src="{% static '/imgs/logo-xan-proxy.png' %}" alt="logo"></li>
                <li class="hideOnMobile"><a href="{% url 'index' %}">Inicio</a></li>
                <li class="hideOnMobile"><a href="{% url 'info' %}">Sobre Xan</a></li>
                <li class="hideOnMobile"><a href="{% url 'portafolio' %}">Portafolio</a></li>
                <li class="hideOnMobile"><a href="{% url 'patreon' %}">Comisiones</a></li>
                <li class="hideOnMobile"><a href="{% url 'referencia' %}">Referencias</a></li>

                {% if perms.web.add_producto %}
                <li class="hideOnMobile"><a href="">Agregar Prod.</a></li>
                {% endif %}
                {% if perms.web.view_producto %}
                <li class="hideOnMobile"><a href="{% url 'listar_producto' %}">Listado de Prod.</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                    </form>
                </li>
                <li>
                    <a href="">@{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Iniciar sesión</a>
                </li>
                {% endif %}

                <li class="menu-button" onclick=showSidebar()><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                  </svg></i></a></li>

            </ul>
        </nav>
    </header>
    <!-- Fin menu -->

        {% load crispy_forms_tags %}

            <div class="row">
                <div class="col-12 col-md-6 offset-md-3">
                    <div class="card">
                        <div class="card-body">
                            <h2>Nuevo producto</h2>
                            <hr>
                            <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <div class="d-flex justify-content-end">
                               <input type="reset" value="Cancelar" class="btn btn-secondary">
                               &nbsp;
                              <input type="submit" value="Guardar" class="btn btn-primary">
                            </div>
                        
                            </form>

                        </div>
                    </div>


                </div>
            </div>








    <!-- Inicio Footer -->
    <footer class="pie"> <!--se inicia creacion de footer -->
        <div class="grupo-1"><!--division de la imagen izquierda xan's proxy -->
            <div class="caja"> <!--division para el contenedor de el logo correspondiente en la parte izquierda de nuestro footer -->
                <figure><!-- apertura figura  -->
                    <img src="{% static '/imgs/logo-xan-proxy.png' %}" alt="logo xan proxy"><!--se añade la imagen o logo correspondiente a esta -->
                </figure><!--cierre de ingreso de logo -->
            </div><!-- cierre de division de la figura -->
            <div class="caja"> <!-- caja para agregar a los integrantes-->
                <h2>Integrantes</h2> <!-- Titulo pequeño para mostrar sobre los integrantes-->
                <p>Sthefanie "Sami" Castro <br>Jonathan "Dexus" Choque <br>Diego "Miza" Pacheco</p><!-- integrante-->
                <p></p><!-- integrante-->
                <p></p><!-- integrante-->
            </div><!--cierre division caja -->
            <div class="caja"> <!--nueva caja para los links de interés -->
                <h2>Siguenos</h2><!--titulo de esta en tamaño h2--> 
                <div class="redes"> <!--clase redes -->
                    <a href="https://github.com/MizaBard" target="_blank"><i class="bi bi-github"></i></a><!--ancla(anchor) github -->
                    <a href="https://www.instagram.com/purenonsince/" target="_blank"><i class="bi bi-instagram"></i></a><!--ancla(anchor) instagram -->
                    <a href="https://twitter.com/MizaSenpai" target="_blank"><i class="bi bi-twitter-x"></i></a><!--ancla(anchor) Twitter "X"(actualmente)-->
                </div><!--cierre de clase redes  -->
            </div><!--cierre de la caja -->
        </div><!--Cierre de clase grupo 1 es la parte "superior" de nuestro footer"pie de página" -->
        <div class="grupo-2"><!--abrimos otra division para la parte inferior de nuestro footer(pie de página) -->
            <small>&copy; 2024 <b>Xan Proxy</b> - Todos los derechos reservados.</small><!--(small comentario pequeño), b(texto el cual no afectará)añade texto extra -->
        </div><!--cierre de la division  -->
    </footer> <!--cierre de seccion de footer -->
    <!-- Fin Footer -->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title" : "Felicitaciones",
                    "text" : "{{m}}",
                    "icon" : "success"
                })
            </script>
        {% endfor %}
    {% endif %}



<!-- inicio de funciones de javascript para el header-->
<script> /*apertura de javascript */
    function showSidebar(){
        const sidebar = document.querySelector('.sidebar')
        sidebar.style.display = 'flex'
    }
    function hideSidebar(){
        const sidebar = document.querySelector('.sidebar')
        sidebar.style.display = 'none'
    }
</script><!--cierre de javascript -->
<!-- fin de las funciones de javascript -->
</body>
</html>

web/templates/web/producto/listar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap, iconos de bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- hojas de estilos, css, fuentes, colores-->
    <link rel="stylesheet" href="{% static '/CSS/menu.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/carrusel.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/style_footer.css' %}">
    <link rel="stylesheet" href="{% static '/CSS/paragraph_index.css' %}"> 
    <!-- fin de imports de estilo (css) -->
    <!-- Favicon, icono de la pestaña, luego va el tamaño(para diferentes tipo de dispositivo)-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/imgs/favicon/apple-touch-icon.png' %}"><!-- este es para apple-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/imgs/favicon/avicon-32x32.png' %}"><!-- este es para windows-->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/imgs/favicon/favicon-16x16.png' %}"><!-- este es para android-->
    <link rel="manifest" href="{% static '/imgs/favicon/site.webmanifest' %}">
    <!-- fin Favicon -->

    <title>Xan Proxy</title> <!--Titulo de las pestañas -->
</head>

<body>
    <!-- menu -->
    <header class="header"> <!--Clase header-->
        <nav> <!--Nav viene de la palabra navigator o sea esta nos mandará a los links que esten dentro de esta misma o los podemos redireccionar donde sea deseado-->
            <ul class="sidebar"> <!--Clase barra lateral, contiene una lista y anclas(anchors) a las otras paginas de nuestro sitio web-->
                <li onclick=hideSidebar()><a href="#"><i class="bi bi-x-lg"></i></a></li>
                <li><a href="{% url 'index' %}">Inicio</a></li> <!-- link a index-->
                <li><a href="{% url 'info' %}">Sobre Xan</a></li><!-- link a info chan-->
                <li><a href="{% url 'portafolio' %}">Portafolio</a></li><!-- link a portafolio de imagenes-->
                <li><a href="{% url 'patreon' %}">Comisiones</a></li> <!--Link a patreon-->
                <li><a href="{% url 'referencia' %}">Referencias</a></li>

                {% if perms.web.add_producto %}
                <li><a href="{% url 'agregar_producto' %}">Agregar Prod.</a></li>
                {% endif %}

                {% if perms.web.view_producto %}
                <li><a href="">Listado de Prod.</a></li>
                {% endif %}
                
                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                    </form>
                </li>
                <li>
                    <a href="#">@{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Iniciar sesión</a>
                </li>
                {% endif %}


            </ul> <!--unordered list -->
            <ul> <!--Esto cambia si es que lo veo de mi dispositivo movil  y me agrega un pequeño boton de menu lateral en la esquina superior izquierda-->
                <li><img src="{% static '/imgs/logo-xan-proxy.png' %}" alt="logo"></li>
                <li class="hideOnMobile"><a href="{% url 'index' %}">Inicio</a></li>
                <li class="hideOnMobile"><a href="{% url 'info' %}">Sobre Xan</a></li>
                <li class="hideOnMobile"><a href="{% url 'portafolio' %}">Portafolio</a></li>
                <li class="hideOnMobile"><a href="{% url 'patreon' %}">Comisiones</a></li>
                <li class="hideOnMobile"><a href="{% url 'referencia' %}">Referencias</a></li>

                {% if perms.web.add_producto %}
                <li class="hideOnMobile"><a href="{%  url 'agregar_producto' %}">Agregar Prod.</a></li>
                {% endif %}
                {% if perms.web.view_producto %}
                <li><a href="">Listado de Prod.</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                    </form>
                </li>
                <li>
                    <a href="">@{{ user.username }}</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Iniciar sesión</a>
                </li>
                {% endif %}

                <li class="menu-button" onclick=showSidebar()><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                  </svg></i></a></li>

            </ul>
        </nav>
    </header>
    <!-- Fin menu -->

    {% load humanize %}
  
    

    <div class="card">
        <div class="card-body">
            <h2>Listado de productos</h2>

            <table class="table table-striped table-hover table-responsive-sm">
                <tr>
                    <th>ID #</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Opciones</th>
                </tr>
        
                {% for p in entity %}
        
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.nombre | title }}</td>
                    <td>${{ p.precio | intcomma }}</td>
                    <td>
                        {% if perms.web.change_producto %}
                        <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info">Modificar</a>
                        {% endif %}

                        {% if perms.web.delete_producto %}
                        <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger">Eliminar</a>
                        {% endif %}

                    </td>
                </tr>
        
                {% endfor %}
        
            </table>

            <div>
                {% include 'web/paginator.html' %}
            </div>

        </div>
    </div>
    




    <!-- Inicio Footer -->
    <footer class="pie"> <!--se inicia creacion de footer -->
        <div class="grupo-1"><!--division de la imagen izquierda xan's proxy -->
            <div class="caja"> <!--division para el contenedor de el logo correspondiente en la parte izquierda de nuestro footer -->
                <figure><!-- apertura figura  -->
                    <img src="{% static '/imgs/logo-xan-proxy.png' %}" alt="logo xan proxy"><!--se añade la imagen o logo correspondiente a esta -->
                </figure><!--cierre de ingreso de logo -->
            </div><!-- cierre de division de la figura -->
            <div class="caja"> <!-- caja para agregar a los integrantes-->
                <h2>Integrantes</h2> <!-- Titulo pequeño para mostrar sobre los integrantes-->
                <p>Sthefanie "Sami" Castro <br>Jonathan "Dexus" Choque <br>Diego "Miza" Pacheco</p><!-- integrante-->
                <p></p><!-- integrante-->
                <p></p><!-- integrante-->
            </div><!--cierre division caja -->
            <div class="caja"> <!--nueva caja para los links de interés -->
                <h2>Siguenos</h2><!--titulo de esta en tamaño h2--> 
                <div class="redes"> <!--clase redes -->
                    <a href="https://github.com/MizaBard" target="_blank"><i class="bi bi-github"></i></a><!--ancla(anchor) github -->
                    <a href="https://www.instagram.com/purenonsince/" target="_blank"><i class="bi bi-instagram"></i></a><!--ancla(anchor) instagram -->
                    <a href="https://twitter.com/MizaSenpai" target="_blank"><i class="bi bi-twitter-x"></i></a><!--ancla(anchor) Twitter "X"(actualmente)-->
                </div><!--cierre de clase redes  -->
            </div><!--cierre de la caja -->
        </div><!--Cierre de clase grupo 1 es la parte "superior" de nuestro footer"pie de página" -->
        <div class="grupo-2"><!--abrimos otra division para la parte inferior de nuestro footer(pie de página) -->
            <small>&copy; 2024 <b>Xan Proxy</b> - Todos los derechos reservados.</small><!--(small comentario pequeño), b(texto el cual no afectará)añade texto extra -->
        </div><!--cierre de la division  -->
    </footer> <!--cierre de seccion de footer -->
    <!-- Fin Footer -->


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title" : "Felicitaciones",
                    "text" : "{{m}}",
                    "icon" : "success"
                })
            </script>
        {% endfor %}
    {% endif %}

    <script>
        function eliminarProducto(id) {
            Swal.fire({
                "title" : "¿Estas seguro?",
                "text" : "esta accion no se puede deshacer",
                "icon" : "question",
                "showCancelButton": true,
                "cancelButtonText" : "No, Cancelar",
                "confirmButtonText" : "Si, Eliminar",
            })
            .then(function(result) {
                if(result. isConfirmed) {
                    window.location.href = "/eliminar-producto/"+id+"/"
                }
            })
        }
    </script>
<!-- inicio de funciones de javascript para el header-->
    <script> /*apertura de javascript */
        function showSidebar(){
            const sidebar = document.querySelector('.sidebar')
            sidebar.style.display = 'flex'
        }
        function hideSidebar(){
            const sidebar = document.querySelector('.sidebar')
            sidebar.style.display = 'none'
        }
    </script><!--cierre de javascript -->
    <!-- fin de las funciones de javascript -->
</body>
</html>